server:
  port: 18083
spring:
  application:
    name: canal
  redis:
    host: 192.168.211.132
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
canal.client.instances.example.host: 192.168.211.132
canal.client.instances.example.port: 11111
canal.client.instances.example.batchSize: 1000
