server:
  port: 7001
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false   #是否将自己注册到eureka中
    fetchRegistry: false         #是否从eureka中获取信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
